<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $oHelper = Mage::helper('sitewards_multipleorder') ?>
<ul class="messages" style="display: none;">
    <li class="error-msg">
        <ul>
            <li></li>
        </ul>
    </li>
</ul>
<div class="fieldset">
    <form method="POST" id="order_form" action="<?php echo $this->getUrl('multipleorder/order/submit'); ?>">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
        <table>
            <thead>
            <tr>
                <th><?php echo $oHelper->__('SKU'); ?></th>
                <th><?php echo $oHelper->__('Name'); ?></th>
                <th><?php echo $oHelper->__('Price'); ?></th>
                <th><?php echo $oHelper->__('Quantity'); ?></th>
                <th><?php echo $oHelper->__('Action'); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr class="product">
                <td><input type="text" name="sku[]" class="sku input-text"/></td>
                <td class="name"></td>
                <td class="price"></td>
                <td><input type="text" name="qty[]" class="qty input-text" disabled="disabled"/></td>
                <td><a class="remove"><?php echo $oHelper->__('Remove this entry'); ?></a></td>
            </tr>
            </tbody>
        </table>
        <input type="submit" value="<?php echo $oHelper->__('Submit Data') ?>"
               title="<?php echo $oHelper->__('Submit Data') ?>"/>
    </form>
    <div class="invisible">
        <img class="loading" src="<?php echo $this->getSkinUrl('images/sitewards/multipleorder/loading.gif'); ?>"/>
    </div>
</div>
<script type="text/javascript">
    Translator.add('The product does not exist.', '<?php echo $oHelper->__('The product does not exist.')?>');
</script>