<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $oHelper = Mage::helper('sitewards_quickorders') ?>
<ul class="messages" style="display: none;">
    <li class="error-msg">
        <ul>
            <li><?php echo Mage::registry('message'); ?></li>
        </ul>
    </li>
</ul>
<div class="category-products quick-list" id="products-list">
<div class="ac-product-list">
<div class="fieldset" data-storeurl="<?php echo  Mage::getBaseUrl(); ?>">
    <form method="POST" id="order_form" action="<?php echo $this->getUrl('quickorders/order/submit'); ?>">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
        <table class="data-table" role="grid">
            <thead>
            <tr>
                <th class="product-code"><?php echo $oHelper->__('Product code'); ?></th>
				<th class="accept"></th>
				<th class="image"><?php echo $oHelper->__('Image'); ?></th>
                <th class="name"><?php echo $oHelper->__('Name'); ?></th>
                <th class="availabilitya" style="display:none;"><?php echo $oHelper->__('Availability'); ?></th>
                <th class="price"><?php echo $oHelper->__('Price'); ?></th>
                <th class="finalprice"></th>
                <th class="qty"><?php echo $oHelper->__('Quantity'); ?></th>
                <th class="remove"style="text-align: right;"><?php echo $oHelper->__('Action'); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr class="product">
                <td class="product-code"><input type="text" name="sku[]" class="sku input-text"/></td>
                <td class="accept">    
					<a href="#"><i class="fi-check"></i></a>
					<div class="invisible">
						<img class="loading" src="<?php echo $this->getSkinUrl('images/loading.gif'); ?>"/>
					</div>
				</td>
				 <td class="img"></td>
                <td class="name"></td>
                <td class="availability" style="display:none;"></td>
                <td class="price"></td>
				<td class="finalprice"></td>

                <td class="qty" id="test">
				<input type="text" name="qty[]" class="qty input-text" disabled="disabled" id="txtQuantity"/>
				</td>
                <td class="remove" style="text-align: center;">
				
				<a class="remove" style="font-size:24px" ><i class="fi-minus-circle"></i></a></td>
            </tr>
            </tbody>
        </table>
		<button type="submit" value="<?php echo $oHelper->__('Submit Data') ?>">
		<i class="fi-shopping-cart" style="margin-right: 1em;"></i>
		<?php echo $this->__('Add products to Cart and go to Checkout'); ?>
		</button>
	


    </form>
</div>
</div>
</div>
<script type="text/javascript">
    Translator.add('The product does not exist.', '<?php echo $oHelper->__('The product does not exist.')?>');
</script>
